version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  ui-tests:
    docker:
      - image: selenium/standalone-chrome
    
    steps:
      - checkout
      
          
      

      - run:
          name: Clear npm cache
          command: npm cache clean --force
      
      - run:
          name: Install Nightwatch
          command: npm install nightwatch

      - run:
          name: Change Nightwatch permissions
          command: sudo chmod +x node_modules/.bin/nightwatch

      - run:
          name: Run Nightwatch tests
          command: sudo npx nightwatch

  api-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Clear npm cache
          command: npm cache clean --force

      - run:
          name: Install Mocha
          command: npm install mocha nodemon --save-dev

      - run:
          name: Change Mocha permissions
          command: sudo chmod +x node_modules/.bin/mocha
      - run:
          name: Change mock-user-auth permissions
          command: chmod +x ./node_modules/mock-user-auth/bin/www.js



      - run:
          name: Start backend server
          command: npm run dev & sleep 10 & npm test
       


  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - ui-tests
      - api-tests
