version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.4

jobs:
  ui-tests:
    docker:
      - image: circleci/node:latest
    
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: 116.0.5845.96
          replace-existing: true
          firefox-version: 80.0.1
      - run:
          command: |
            google-chrome --version
            firefox --version
            geckodriver --version
            chromedriver --version
            java -jar /usr/local/bin/selenium.jar --version
          name: Check install

      - run:
          name: Clear npm cache
          command: npm cache clean --force
      
      - run:
          name: Install Nightwatch
          command: npm install nightwatch

      - run:
          name: Change Nightwatch permissions
          command: sudo chmod +x node_modules/.bin/nightwatch

      - run:
          name: Run Nightwatch tests
          command: sudo npx nightwatch

  api-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Start backend server
          command: npm run dev &

      - run:
          name: Run API tests
          command: npm test

  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - ui-tests
      #- api-tests
