version: 2.1

orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.4.4

jobs:
  ui-tests:
    docker:
      - image: circleci/node:latest
    
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: 116.0.5845.96
          
      - run:
          command: |
            google-chrome --version
            
            
            chromedriver --version
            
          name: Check install

      - run:
          name: Clear npm cache
          command: npm cache clean --force
      
      - run:
          name: Install Nightwatch
          command: npm install nightwatch

      - run:
          name: Change Nightwatch permissions
          command: sudo chmod +x node_modules/.bin/nightwatch

      - run:
          name: Run Nightwatch tests
          command: sudo npx nightwatch

  api-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Clear npm cache
          command: npm cache clean --force

      - run:
          name: Install Mocha
          command: npm install mocha nodemon --save-dev

      - run:
          name: Change Mocha permissions
          command: sudo chmod +x node_modules/.bin/mocha
      - run:
          name: Change mock-user-auth permissions
          command: chmod +x ./node_modules/mock-user-auth/bin/www.js



       run:
          name: Start backend server
          command: npm run dev &

      - run:
          name: Wait for server to start
          command: sleep 10  # Adjust sleep time as needed to ensure server is fully started

      - run:
          name: Open New Bash Terminal
          command: |
            sleep 10
            xterm -e 'bash -c "echo New terminal opened!; exec bash"' &

      - run:
          name: Run API tests
          command: npm test


  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - ui-tests
      - api-tests
