version: 2.1

jobs:
  ui-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

      - run:
          name: Clear npm cache
          command: npm cache clean --force

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npx nightwatch
            


  api-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Start backend server
          command: |
            npm run dev &
            


      # Run API tests after the backend server is started
      - run:
          name: Run API tests
          command: npm test
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - ui-tests
      - api-tests
      - build
