version: 2.1

jobs:
  ui-tests:
    docker:
      - image: circleci/node
    steps:
      - checkout

      - run:
          name: Clear npm cache
          command: npm cache clean --force

      - run:
          name: Install Nightwatch
          command: sudo npm install nightwatch -g

      - run:
          name: Display npm logs
          command: |
            cat /root/.npm/_logs/2024-02-06T20_30_07_991Z-debug.log
            cat /root/.npm/_logs/2024-02-06T20_30_08_340Z-debug.log

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Set executable permissions for Nightwatch
          command: |
            cd node_modules/.bin && chmod +x nightwatch && nightwatch



  api-tests:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Start backend server
          command: |
            npm run dev &
            


      # Run API tests after the backend server is started
      - run:
          name: Run API tests
          command: npm test
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - ui-tests
      - api-tests
      - build

